# Generated by Django 5.2.5 on 2025-08-20 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_base64', models.TextField()),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_categorias', to='livraria.categoria')),
            ],
        ),
    ]
