# Generated by Django 5.2.5 on 2025-08-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0003_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='quantidade_estoque',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
